I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 219, in script
    with fadeHold
  File "game/script.rpy", line 219, in <module>
    with fadeHold
NameError: name 'fadeHold' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 219, in script
    with fadeHold
  File "C:\Users\barba\OneDrive\Escritorio\renpy-8.3.2\renpy\ast.py", line 1354, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\barba\OneDrive\Escritorio\renpy-8.3.2\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\barba\OneDrive\Escritorio\renpy-8.3.2\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 219, in <module>
    with fadeHold
NameError: name 'fadeHold' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
a_golden_chance 1.0
Mon Nov 11 19:40:30 2024
